### ISSUE TITLE
Translating text doesn't work

### ISSUE THREAD

**Issue by CatzTimes** [ShimmyMySherbet/SherbetHome#1]
After I tried to translate it into Chinese, the plugin did not show any errors when loading, but I found that the translation file did not work in the game...

**Comment by ShimmyMySherbet** [comment]
If you're having issues after modifying the translations file, you have most likely broken it.
You can check for errors using an online XML validation tool. E.g., https://www.xmlvalidation.com/

**Comment by CatzTimes** [comment]
Checked the website and found no errors

**Comment by CatzMR** [comment]
SherbetVaults.en.translation
---
<?xml version="1.0" encoding="utf-8"?>
<Translations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Translation Id="Vault_Fail_NotFound" Value="[color=red]找不到该 ID 的跨服背包[/color]" />
  <Translation Id="Vault_Fail_NoPermission" Value="[color=red]您无权访问跨服背包 {0}[/color]" />
  <Translation Id="Vault_Fail_CannotLoad" Value="[color=red]保险柜 {0} 目前不可用[/color]" />
  <Translation Id="Vaults_No_Vaults" Value="[color=yellow]您无权访问任何跨服背包[/color]" />
  <Translation Id="Vaults_List" Value="[color=green]您的跨服背包：{0}[/color]" />
  <Translation Id="WipeVault_Wiped" Value="[color=green]从 {1} 的跨服背包 {2}[/color] 中擦除了 {0} 项" />
</Translations>

**Comment by CatzMR** [comment]
SherbetHome.en.translation
-
<?xml version="1.0" encoding="utf-8"?>
<Translations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Translation Id="Home_Fail_NoBed" Value="[color=red]您的床被堵住或丢失了[/color]" />
  <Translation Id="Home_Fail_AlreadyPending" Value="[color=red]已经传送回家[/color]" />
  <Translation Id="Home_Wait" Value="[color=yellow]传送回家，等待 {0} 秒...[/color]" />
  <Translation Id="Home_Failed_Move" Value="[color=red]因为你移动而取消传送[/color]" />
  <Translation Id="Home_Teleported" Value="[color=green]传送到你的床[/color]" />
  <Translation Id="Home_Failed_Blocked" Value="[color=red]传送失败，因为你的床被挡住或损坏了[/color]" />
</Translations>

**Comment by CatzTimes** [comment]
https://github.com/CatzMR/Unturned-BUG/blob/master/SherbetHome.en.translation.xml
and
https://github.com/CatzMR/Unturned-BUG/blob/master/SherbetVaults.en.translation.xml

**Comment by ShimmyMySherbet** [comment]
Looking into it, it appears to be an issue with RocketExtensions always using the default translations, instead of the custom ones. I will update both plugins now.

**Comment by CatzTimes** [comment]
sorry to bother you, thank you

**Comment by ShimmyMySherbet** [comment]
This issue has been amended in <a href="https://github.com/ShimmyMySherbet/SherbetHome/releases/tag/1.2">v1.2</a>

**Comment by ShimmyMySherbet** [comment]
Let me know if you still have any issues.
