### ISSUE TITLE
Home Cooldown!

### ISSUE THREAD

**Issue by MihailHavenT** [ShimmyMySherbet/SherbetHome#2]
A home cooldown should be added when a player has successfully teleported to their bed... not when the teleportation failed!

i.g Tra
`  <Translation Id="Home_Cooldown" Value="[color=red]You have to wait {0} to use this command again[/color]" />`

**Comment by ShimmyMySherbet** [comment]
This issue has been amended in <a href="https://github.com/ShimmyMySherbet/SherbetHome/releases/tag/1.2">v1.2</a>

**Comment by ShimmyMySherbet** [comment]
Let me know if you have any issues with the latest update.
