### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by PinkerTee** [ShimmyMySherbet/SherbetHome#3]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/82455f9a-dd27-4225-a950-29fd01fbf950)

i have no clue what i am doing wrong

![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/417e137c-a59e-4fcc-b4fe-83ce780cd6c7)
 it doesnt show that the command is not found. it simply does nothing when i type /home

**Comment by ShimmyMySherbet** [comment]
Could you send your server log? It's located at Rocket\Logs\latest.log

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/c032ea86-ea43-4808-accd-b00e681e892e)
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/61d6c5f9-1359-4555-956a-7e99b269f215)
[Rocket.log](https://github.com/ShimmyMySherbet/SherbetHome/files/12677603/Rocket.log)
the log is the one from the bottom called rocket.log dunno if its the right one

**Comment by ShimmyMySherbet** [comment]
Looking through your log, I cam see a couple issues. Sherbet Home is missing the netstandard library. I was under the impression it was now being included with Unturned, but it seems otherwise. I've attached the netstandard.dll library for you to add to your Libraries folder: [netstandard.zip](https://github.com/ShimmyMySherbet/SherbetHome/files/12678702/netstandard.zip).

Additionally, I can see an issue with SherbetVault, you're missing the library 'Ubiety.Dns.Core.dll'. So you might want to re-install the plugin (https://github.com/ShimmyMySherbet/SherbetVaults/releases/tag/v1.2)

I deleted your message as your log contained some sensitive information that's best not to leave here.

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/1f3dfc0c-755d-4e45-a27d-7677ac25d8c2)
this is all i get in the libraries folder when i unpack the zip files
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/d5d964aa-1faa-4637-a796-31639187ca0e)

i've tried /home wit the netstandard.dll and it works. now its just the vault ty already bruv

sorry for causing this inconvenience and thank your patience man

**Comment by ShimmyMySherbet** [comment]
I looked into it, and it turns out the library was mistakenly had copy-local disabled for SherbetVaults, meaning it was missing in the release.
I'm surprised it took this long to pick up on, though this issue would only be seen on servers with no other plugins using MySQL, such as yours.
I've released another revision to  fix this.
Downloading the latest revision of SherbetVaults and re-installing it should fix the issue. Let me know if everything works after that.
https://github.com/ShimmyMySherbet/SherbetVaults/releases/tag/v1.2

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/67e3640a-d809-4b4d-b55e-d620e3315ed1)
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/d1c3a94e-1b73-40be-a042-d449d004c5c2)
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/cd9ebe60-5290-4c45-9925-d31f32baaa54)
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/e7b50c9e-7d3f-4e2a-95f2-19845bfdadc3)
 vault doesnt work. maybe i am doing smth wrong?

**Comment by ShimmyMySherbet** [comment]
Could you upload your log again?

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/7ef6b3eb-3416-430a-869f-3a2e2131b6fd)
[Rocket.log](https://github.com/ShimmyMySherbet/SherbetHome/files/12684165/Rocket.log)

**Comment by ShimmyMySherbet** [comment]
> "Failed to connect to database: Unable to connect to any of the specified MySQL hosts."

You haven't set the plugin up. You need to fill out your database details in the plugin config.

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/5f8ee473-8b4f-4129-bca7-e495f9a639ae)
 in app config?
if so, r there any sensitive infos in there or can i send a screenshot of the config i need to edit

**Comment by ShimmyMySherbet** [comment]
No, the config file in the SherbetVaults folder

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/dd3b9544-9d43-4bc3-9def-8a40380ce2a0)
 this one?

**Comment by ShimmyMySherbet** [comment]
Yep, that's it

**Comment by PinkerTee** [comment]
what data has to go in there? like i said, im sorry but this is the first time i am doing this stuff

**Comment by ShimmyMySherbet** [comment]
Your database settings. Are you using a server host, or are you hosting it yourself?

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/648fe157-aa75-43b1-be8b-14c10fc73fc8)
in there right? where it says username password etc. right?

**Comment by ShimmyMySherbet** [comment]
Yea, you need to put your database username & password in there, along with the database name and address if needed.

**Comment by PinkerTee** [comment]
i am hosting the server with a friend but i have access to the hosting website. does it take the ftp stuff or the Mysql
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/912b0914-737f-4633-badd-76eaaa332161)
 or is it the username and password of the website itself

**Comment by ShimmyMySherbet** [comment]
The username and password depends on your hoster. There should be a section on mysql credentials. If I had to assume it would be the instructions button in that screenshot.

**Comment by PinkerTee** [comment]
i see the mysql stuff, it says it right below it. I just didnt screenshot it because i dont know if thats sensitive information.
it shows a hostname, port,username, password,database and smth called "phpMyAdmin" which is a link

**Comment by PinkerTee** [comment]
for databaseAdress do i need the hostname? 
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/4dd6323f-71c7-4940-bc82-d68c5852269d)
this isnt the full number, i just wanted to give an example

**Comment by ShimmyMySherbet** [comment]
Yep, the hostname is the value you want for DatabaseAddress, that database field is what you want for DatabaseAddress.
That's all the info you need.

**Comment by ShimmyMySherbet** [comment]
PhpMyAdmin is a web interface to manage the database, you won't need it for now.

**Comment by PinkerTee** [comment]
ok, i filled in the info, the default permission vault says width 8 height 8 can i change the size of the vault there?

**Comment by ShimmyMySherbet** [comment]
Yep

**Comment by PinkerTee** [comment]
now it should work?
the /vault command

**Comment by ShimmyMySherbet** [comment]
Should do. You might also want to setup permissions so your players can use the command as well. But now is a good time to make sure everything is working

**Comment by PinkerTee** [comment]
isnt the permission "default" for everyone?

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/004df9bf-e147-44a4-a88a-9d009f2cb388)
i have to give you big thanks bruv, the vault command works fine now atleast /vault. ima see what else commands r in and try them

**Comment by PinkerTee** [comment]
now to the garage plugin xD. ima go and download it or do you want to send me the link here

**Comment by PinkerTee** [comment]
oh, nvm you dont have a garage plugin :/ mb

**Comment by ShimmyMySherbet** [comment]
Yea, I don't have any public garage plugin. I had one that I was going to sell on ImperialPlugins, but never ended up doing so.
I might just publish my old garage plugin for free at this point.

**Comment by PinkerTee** [comment]
will you? i would love to use it since i am already using your home and vault and since you've been so nice to help me with all of this stuff xD even tho i am very "doo doo" at this

**Comment by ShimmyMySherbet** [comment]
Would require some work to update and get going again, so def couldn't do it today.

**Comment by PinkerTee** [comment]
ahhh, do you know a other garage plugin thats easy to get running? i have a vehicle mod on the server and idk if the vehicles spawn so i would just wait a few days and if no one has any of the cars i would spawn em for them and it would b a shame if people were just able to destroy them while raiding

**Comment by ShimmyMySherbet** [comment]
I don't know of any free garage plugins unfortunately, though you could just search github for one.

**Comment by PinkerTee** [comment]
i will def do that, but first you said i need to change permissions for the vault. what do i have to change it to

**Comment by ShimmyMySherbet** [comment]
Ah, yes.
To allow players to access vault, you'll need to give them the permissions `vault`, `vaults`, and `vault.default`.
You can assign permissions in the permissions.config.xml file in the rocket folder.
There should be 2 groups in it by default, and the group you want to add those permissions to will be the default group.

Same goes for any other commands you want to allow your players to use. Including `home`.

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/5f842201-3531-4a0e-b9dc-433fd0f15986)
 in this?

**Comment by ShimmyMySherbet** [comment]
Yep. You'll want to add more permissions to the `<Permissions>` section.
The format to add a permission is `<Permission Cooldown="0">Permission</Permission>`
Where 0 is the cooldown in seconds, for commands. And `Permission` is the permission value.

The permission value can be a command name, or a specific permission value such as `vault.default`.

**Comment by PinkerTee** [comment]
So i can write it <Permission Cooldown="3">vault.default</Permission> or is that wrong

**Comment by ShimmyMySherbet** [comment]
For the permission value yes, so it would be `<Permission Cooldown="0">vault.default</Permission>`

**Comment by PinkerTee** [comment]
oh lol it didnt show it in my message tf, it just says vault.default 
didnt see that xD

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/d2428bc0-5d72-4c42-baa9-975cfd434826)
 would this work for home too?

**Comment by ShimmyMySherbet** [comment]
for home, it should just be `home`. `vault.default` gives permission to the vault `default`.

You also need to add `vault` (to give access to /vault), and `vaults` (for /vaults, to see what vaults you have)

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/72647ac8-11f0-4f09-b9cd-0e381190092c)
 like this?

**Comment by ShimmyMySherbet** [comment]
Not sure if it's just not in the screenshot, but you need `vault` as well as `vaults`

**Comment by ShimmyMySherbet** [comment]
as they are different commands and permissions

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/30f0b787-07a9-4e9d-b8b1-983cb008fadb)

**Comment by PinkerTee** [comment]
ah and since i have a tpa plugin too i need to do the same for tpa tpa deny and all of that too?

**Comment by ShimmyMySherbet** [comment]
Yep, though it should just be `tpa`. I'll double check now

**Comment by PinkerTee** [comment]
ah ok, ty bruv

**Comment by ShimmyMySherbet** [comment]
Yep, all you need to assign is `tpa`.

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/74f39688-f3f7-4e3f-b7ee-da57de83b3da)
 so i can delete tpa d,a,c again?

do i need to add .default to tpa?

**Comment by ShimmyMySherbet** [comment]
All you need is `tpa`, you don't need to do anything for d, a, or c.

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/cfc17dd5-b9ed-46d2-8c16-75ba9566b704)
 so i just need this

**Comment by ShimmyMySherbet** [comment]
That should be good

**Comment by PinkerTee** [comment]
![image](https://github.com/ShimmyMySherbet/SherbetHome/assets/145491740/4628cbf6-b9b1-4d13-b871-4f09317f2d38)
does this stand for the group that im assigning permission to? or why dont i need to add default or anything to tpa ( i want to understand it so maybe i can help myself next time and dont have to take other peoples time ^^' sorry)

**Comment by ShimmyMySherbet** [comment]
That field normally contains the player IDs of people in the group. However it isn't used for the `default` group, as every player has the group.

If you look at the `vip` group below it, you can see the `<Members>` area has a Player ID, of one of the developers of RocketMod. So only players whose ID is in the members section gets those permissions

**Comment by PinkerTee** [comment]
ok so everyone new just gets the member "rank" and those have the permissions i assigned for the commands then?

**Comment by PinkerTee** [comment]
and also, i saw a vip vault. does the vip have to be assigned by an admin or is that for the gold version of unturned. and if it has to be assigned by an admin. how to assign it? just /vip "steam id" ?

**Comment by ShimmyMySherbet** [comment]
The vip group is just there as a template, so you can copy and paste it to create your own groups. You don't have to worry about it, as none of your players will be in the vip group.

All players have the permissions from the `default` group, which is why we added the vault permissions to it, as well as any additional groups you add them to.

**Comment by PinkerTee** [comment]
ok ty, i have one last question

i have installed mods for weapons etc. they r like 3 or 4 weapon mods but only one of them is dropping items and i dont understand it. do i have to enable drops somewhere?

**Comment by ShimmyMySherbet** [comment]
No, the items from the modpack will be added to the server's item spawn tables automatically, so long as the mod does come with spawn tables. Not all mods do, and there is no way to add them to the maps spawn tables manually.

The items from those mods are typically included in the spawn tables of custom maps, or can be distributed to players in the form of a shop.

For the sake of simplicity, for now I do not recommend trying to set up a shop, as they're a time consuming and finicky thing to set up. And can destroy your server economy if done incorrectly.

**Comment by PinkerTee** [comment]
yeah i ain adding a shop system, im tryin to make a oldschool modded server. none of that new bs with shop, warps. /back. safezones etc. just oldschool keep skills a lil higher loot and basic commands

is there any way to find out if a mod has spawn tables for vanilla maps except trying it out? (btw the items dont even drop from zombies) thats why i was so confused, cuz if they dont spawn on the map thats ok as long as they drop from zombies

**Comment by ShimmyMySherbet** [comment]
Unfortunately there isn't any easy way to know if a mod will spawn items naturally on vanilla maps. The only way to really tell is if they tell you it does on the workshop page, or you test it yourself. Which would likely include just playing the game for a while.
Though most mods *should* yell you on the workshop page.

**Comment by PinkerTee** [comment]
ah ok, thank you man for your time and help. i really appreciate your patience and being so nice. have a very wonderful day/week

**Comment by ShimmyMySherbet** [comment]
No worries, and good luck with your server
